### ISSUE TITLE
Issue regarding running web server

### ISSUE THREAD

**Issue by jihoon-seo** [practice-golang/9minutes#2]
@practice-golang 안녕하세요~~

제가 구분 게시판을 한 번 실행해 보려고 했는데, 잘 되지 않아 이슈를 남겨 봅니다. 😊

[환경]
- Ubuntu 18.04 amd64 desktop (VM)
- go 1.16.7

[절차]
- `make`
  - `bin/` 에 `9minutes` 바이너리가 만들어졌습니다.
- `cd bin`
- `./9minutes`

```
2021/09/14 17:02:36 Fail to read ini. 
2021/09/14 17:02:36 9minutes.ini is created
⇨ http server started on 127.0.0.1:2510
```

- 이 때, 개발 VM에서 http://localhost:2510/ 으로 접속하면 페이지가 뜨는데,
  개발 VM과 같은 LAN에 있는 다른 컴퓨터에서는 접속이 안 됩니다.
  (listen을 0.0.0.0:2510 이 아니라 127.0.0.1:2510 으로 하고 있는 것 같은 현상)
![image](https://user-images.githubusercontent.com/46767780/133220149-14e9b282-41c5-4497-9495-b9197aa0768f.png)

- `./9minutes` 바이너리를 종료하면 
  `bin/` 디렉토리에 여러 파일이 생성되어 있습니다.
  - `9minutes.db`
  - `9minutes.ini`
  - `connection.log`
  - `request-body.log`

- `9minutes.ini` 를 열어 보면 다음과 같습니다.

```INI
APP_NAME = 9minutes

[user-defined]
; HTML = false
HTML = true
PATH = "/html"
; PATH = "../html"
; PATH = "files:///C:/Users/swshin/Desktop/pcbangstudio/workspace/9minutes/bin/html"

[server]
ADDRESS = 0.0.0.0
PORT = 2510

; [server]
; ADDRESS = 127.0.0.1
; PORT = 2510

; [server]
; ADDRESS = 0.0.0.0
; PORT = 80

[database]
DBTYPE = sqlite
FILENAME = ./9minutes.db
```

- 다시 `./9minutes` 바이너리를 실행하면
  - 개발 VM에서 http://localhost:2510/ 접속: 404 page not found
  - 개발 VM과 같은 LAN에 있는 다른 컴퓨터에서 http://192.168.1.6:2510/ 접속: 404 page not found

훔.. `9minutes.ini` 가 없는 상태에서 `./9minutes` 바이너리를 실행하면
`9minutes.ini` 파일을 생성하기는 하는데
생성한 `9minutes.ini` 파일의 내용을 읽어서 실행되는 것은 아니고
자체적으로 갖고 있는 default conf 값에 따라 실행되는 것으로 추정되네요.. ㅎㅎ

---

[`9minutes.ini`]
- `PATH = "../static"` 로 설정 후 실행
  => 404 page not found 뜹니다. `bin/` 바깥의 경로는 지정할 수 없는 것으로 보입니다.
- `static/` 디렉토리를 `bin/` 아래에도 복사하고, `PATH = "../static"` 로 설정 후 실행
  => 뭔가 CSS가 적용되지 않은 듯한 화면이 뜹니다.
  ![image](https://user-images.githubusercontent.com/46767780/133226302-3200e0d0-c67e-4eab-b71d-727c64b13f9a.png)
- `static/` 디렉토리를 `bin/` 아래에도 복사하고, `PATH = "./static"` 로 설정 후 실행
  => `PATH = "../static"` 일 때와 마찬가지 입니다.
- `static/` 디렉토리를 `bin/` 아래에도 복사하고, `PATH = "/static"` 로 설정 후 실행
  => 다시 CSS가 적용된 듯한 화면이 뜹니다.
  ![image](https://user-images.githubusercontent.com/46767780/133220149-14e9b282-41c5-4497-9495-b9197aa0768f.png)

---

[질문]
제가 실행한 방법 (`static/` 디렉토리를 `bin/` 아래에도 복사하고, `PATH = "/static"` 로 설정 후 실행) 이 적절한가요? 😊

그리고,
현재 README에는 이렇게 되어 있습니다.

> * Build and run
> * Then stop and edit `9minutes.ini`
> * Then run again
> * Open `http://localhost:2510` in browser
> * Sign in with `admin` / `admin`

여기 어딘가에
"`static/` 또는 `templates` 아래의 파일들을 `bin/html/` 아래로 복사한다" 내용을 넣으면 사람들에게 도움이 되려나요? 😊

**Comment by practice-golang** [comment]
@jihoon-seo 님, 안녕하세요.
알림을 꺼두는 바람에 늦게 봤습니다. 죄송합니다. ㅠㅠ

`9minutes.ini` 파일에서 아래 user-defined 섹션을 주석처리 하신 다음에 실행해보시겠어요?

```ini
[user-defined]
; HTML = false
; HTML = true
; PATH = "/html"
; PATH = "../html"
; PATH = "files:///C:/Users/swshin/Desktop/pcbangstudio/workspace/9minutes/bin/html"
```

프로그램 첫 실행 -> 정지 후에 다시 실행하시면 이 때부터 `ini`파일의 내용을 프로그램이 받아들입니다.

`ini`파일이 없는 상태로 처음 실행 시, `ini` 파일을 `생성만`하게 되어 있고, 수신 설정은 기본값인 `http://127.0.0.1:2510` 으로 하게끔 되어 있습니다.

**Comment by jihoon-seo** [comment]
@practice-golang 안녕하세요 추석 연휴 잘 보내셨나요 😊
알려 주신 대로 해 보니 페이지가 잘 뜹니다. 😊
감사합니다 😊

![image](https://user-images.githubusercontent.com/46767780/134439498-d2183d6a-64e1-41fd-969f-6f287c2732f5.png)

---

다음은 각 메뉴를 클릭해 봤을 때의 결과입니다.
(기록용으로 남겨 봅니다 😊)

- Admin - Board manager: 다시 메인 페이지로 돌아옵니다.
- Admin - User fields: 다시 메인 페이지로 돌아옵니다.
- Admin - User manager: 다시 메인 페이지로 돌아옵니다.
- Login: 로그인 화면
- Logout: 로그아웃 되었다는 sweetalert 메시지
- Join: 가입 회면
- Edit Info: 다시 메인 페이지로 돌아옵니다.

아래는 전부 404 Page not found 가 뜹니다.
- custom table list `#5` / admin / admin / admin
- custom table list `#4` / user / admin / admin
- custom table list `#3` / user / user / user
- custom table list `#2` / all / user / user
- custom table list `#1` / all / all / all
- Custom Board5 / admin / admin / admin
- Custom Board4 / user / admin / user
- Custom Board3 / user / user / user
- Custom Board2 / all / user / user
- Custom Board1 / all / all / all
- Board5 / admin / admin / admin
- Board4 / user / admin / user
- Board3 / user / user/ user
- Board2 / all / user/ user
- Board1 / all / all / all

**Comment by practice-golang** [comment]
@jihoon-seo 안녕하세요.
어드민 계정은 admin/admin 으로 해서 로그인 하시면 위 세개의 Admin - 링크로 진입할 수 있습니다.
Board 들은 admin 로그인 후 Admin - board manager에서 직접 만들어주시거나 저장소에 있는 `requests/*.http` 내용을 참조하셔서 샘플 게시판을 만드실 수 있습니다.
헤더에 admin token이 필요합니다. `request` 디렉토리의 `vscode`/`RestClient` 확장용 파일 참조하시면 됩니다.
